// ── Re-export unique depuis src/types/index.ts ─────────────────────────────
// @/types résout vers ce fichier (priorité fichier > dossier en TypeScript).
// Tout le domaine métier est défini dans src/types/index.ts.
export type {
  RequestStatus,
  UserRole,
  InterventionType,
  InterventionCategory,
  InterventionNature,
  Site,
  Zone,
  Equipment,
  Technician,
  Skill,
  UserProfile,
  DirectionEntityAssignment,
  InterventionSite,
  BonDeLivraison,
  MaintenanceRequest,
  Mission,
  MissionIntervention,
  KpiSnapshot,
  PlanningRunType,
  PlanningRunStatus,
  PlanningRun,
  PlanningEngineConfig,
  ReplanningStrategy,
  MissionReplanningEvent,
  WorkflowStatusRule,
  RequestStatusHistory,
  RequestStatusAlert,
  GroupEntity,
  Supplier,
  PurchaseOrderStatus,
  PurchaseOrder,
  PurchaseOrderLine,
  NotificationLevel,
  NotificationChannel,
  AppNotification,
} from './types/index';
